#ifndef CONFIG_H
#define CONFIG_H

#define SYSTEM_CERSION	"V1.01"
//GUI setting
#define WIDGET_BORDER_WIDTH	1
#define WIDGET_UNDERLINE_WIDTH	1
#define WIDGET_NEXT						BUTTON_RIGHT
#define WIDGET_PREV						BUTTON_LEFT
#define WIDGET_ENTER					BUTTON_ENTER
#define WIDGET_SELECT_BACK_COLOR	LCD_COLOR_WHITE
#define WIDGET_SELECT_TEXT_COLOR	LCD_COLOR_BLACK

#define WIDGET_BUTTON_ENTER		BUTTON_ENTER	
#define WIDGET_BUTTON_NEXT	WIDGET_NEXT
#define WIDGET_BUTTON_PREV	WIDGET_PREV
#define WIDGET_BUTTON_SELECT_BACK_COLOR	WIDGET_SELECT_BACK_COLOR
#define WIDGET_BUTTON_SELECT_TEXT_COLOR	WIDGET_SELECT_TEXT_COLOR


#define WIDGET_EDIT_CONFIRM			BUTTON_ENTER
#define WIDGET_EDIT_CANCEL			BUTTON_ESC
#define WIDGET_EDIT_VALUE_UP 		BUTTON_UP //字符值变大
#define WIDGET_EDIT_VALUE_DOWN 	BUTTON_DOWN		//字符值变小
#define WIDGET_EDIT_NEXT 				BUTTON_RIGHT//上
#define WIDGET_EDIT_PREV 				BUTTON_LEFT//下
#define WIDGET_EDIT_SELECT_BACK_COLOR	LCD_COLOR_WHITE
#define WIDGET_EDIT_SELECT_TEXT_COLOR	LCD_COLOR_BLACK
#endif
