#ifndef SYSTEM_CONFIG_H001
#define	SYSTEM_CONFIG_H001

#define UART_TICK_BUFFER_SIZE	16
#define AUTO_POWER_OFF_TIME 30000

#define MOTOR_TASK_PRIORITY	(tskIDLE_PRIORITY+3)
#define TICK_TASK_PRIORITY			(tskIDLE_PRIORITY+2)
#define EVENTLOOP_TASK_PRIORITY		(tskIDLE_PRIORITY+4)

#define MOTOR_TIMER_IRQ_PRIORITY (configMAX_SYSCALL_INTERRUPT_PRIORITY>>4)
#define DOOR_OPEN_IRQ_PRIORITY (configMAX_SYSCALL_INTERRUPT_PRIORITY>>4)
#define	USB_IRQ_PRIORITY (configMAX_SYSCALL_INTERRUPT_PRIORITY>>6)








#endif

